apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: test
spec:
  replicas: 2
  selector:
     matchLabels:
      app: wordpress
  template:
   metadata:
    labels:
     app: wordpress
   spec:
    containers:
     - name: wordpress
       image: wordpress:latest
       ports:
        - containerPort: 80
       env:
        - name: WORDPRESS_DB_HOST
          value: mydb-service.test.svc.cluster.local:3306
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
               name: user-info
               key: username 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-info
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
               name: db-name
               key: database
