apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: test
spec:
  replicas: 2
  selector:
     matchLabels:
      app: apache
  template:
   metadata:
    labels:
     app: apache
   spec:
    imagePullSecrets:
     - name: dhpasswd
    containers:
     - name: apache
       image: srishu54/my-repo:BUILD_NUMBER
       ports:
        - containerPort: 80
        
